# Generated by Django 2.1.5 on 2019-02-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0003_auto_20190124_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='HockeyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_hockey_team',
            field=models.CharField(default='', max_length=50),
        ),
    ]
