# Generated by Django 2.1.5 on 2019-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0004_auto_20190204_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockeyteam',
            name='id',
        ),
        migrations.AlterField(
            model_name='hockeyteam',
            name='team_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
