# Generated by Django 2.1.5 on 2019-01-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0004_auto_20190130_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='OR', max_length=50),
        ),
    ]
