# Generated by Django 2.1.5 on 2019-02-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0006_auto_20190205_0705'),
        ('DataApp', '0005_auto_20190131_1250'),
    ]

    operations = [
    ]
