# Generated by Django 2.1.5 on 2019-02-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0010_basketballteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_nba_team',
            field=models.CharField(default='', max_length=50),
        ),
    ]
